name: ModifyPRKata

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Modify solutions/git/pull-request-erstellen.md
      run: |
        echo "Write $GITHUB_ACTOR to "GITHUB_WORKSPACE/solutions/git/pull-request-erstellen.md"
        echo $GITHUB_ACTOR >> $GITHUB_WORKSPACE/solutions/git/pull-request-erstellen.md
        cat $GITHUB_WORKSPACE/solutions/git/pull-request-erstellen.md
    - name: Commit files
      run: |
        git config --local user.email "5276337+wulfland@users.noreply.github.com"
        git config --local user.name "Michael Kaufmann"
        git commit -am "Add $GITHUB_ACTOR to pull-request-erstellen.md"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
